[package]
name = "image_duplicates"
version = "0.5.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eframe = { version = "0.31", features = ["default"] }
egui_extras = { version = "0.31", features = ["default", "file", "image"] }
image = { version = "0.25.2", features = [
    "jpeg",
    "png",
    "rayon",
    "webp",
] } # 0.25.1 for egui_extras
rfd = { version = "0.15" }
rayon = "1.10"
crossbeam = "0.8"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "ansi",
    "fmt",
    "env-filter",
] }

[dev-dependencies]
pretty_assertions = "1.4"
criterion = { version = "0.6", features = ["html_reports"] }

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cast_precision_loss = "allow" # for usize to f32 conversion

[profile.release]
codegen-units = 1 # this will slow down the built, but give a 15% increase in performance.
opt-level = 3
lto = "fat"
panic = "abort"
strip = "full" # false for flamegraph analysis
debug = false # true for flamegraph analysis


[features]
default = ["simd"]
simd = []

[[bench]]
name = "correlation_benchmark"
harness = false